version: '3.8'

networks:
  app-network:

volumes:
  app-data:

services:
  puribundasrv:
    image: nginx:1.21.6-alpine
    container_name: puribundasrv
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - .docker/nginx:/etc/nginx/conf.d
    networks:
      app-network:

  puribundabackend:
    build:
      context: .
      dockerfile: .docker/php/dockerfile
    container_name: puribundabackend
    volumes:
      - ./:/var/www
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - .docker/php/php-fpm-settings.conf:/usr/local/etc/php-fpm.d/zzz-php-fpm-settings.conf
      # - .docker/php/logs/php_error.log:/var/log/error.log
      # - .docker/php/logs/php_access.log:/var/log/access.log
    networks:
      app-network:
